version: "2.1"

services:
  k3s:
    # https://docs.k3s.io/advanced#running-k3s-in-docker
    build: k3s
    privileged: true
    network_mode: host
    labels:
      io.balena.features.kernel-modules: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    tmpfs:
      - /run
      - /var/run
    volumes:
      - k3s-data:/var/lib/rancher/k3s

volumes:
  k3s-data: {}
