apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: default
spec:
  secretName: ca-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: selfsigned-issuer # Reference to the selfsigned-issuer
    kind: ClusterIssuer
  commonName: ca.balena.local # Name of the CA
  subject:
    organizations:
    - balena
    organizationalUnits:
    - devops
    localities:
    - Seattle
    provinces:
    - Washington
    countries:
    - US
  isCA: true
  usages:
    - digital signature
    - key encipherment
    - cert sign

