
---
# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: api.${TLD}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              name: http
  - host: caddy.${TLD}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: caddy
            port:
              name: http
